### PR TITLE
source restructured, tcp options added

### PR DESCRIPTION
**Pull request by manu-g**

### CODE REVIEW

**Comment by glaslos** [comment]
Awesome, it might take me some time to review your changes. For the future, I recommend to branch first, then edit files before making a pull request. This way you can always keep your master in sync with the upstream master. Here is a very simple overview on the general workflow: https://guides.github.com/introduction/flow/

**Comment by manu-g** [comment]
thanks for the advise, i will keep it in mind.

**Comment by lceames** [comment]
Manu-g, thanks for the updated version. I tried running it but I'm hitting problems sending PUR(port unreachable) packets. Scapy is erroring out with the following stack trace. Did you ever run into this issue? 

```
Traceback (most recent call last):
  File "/home/elephant/Desktop/oschameleon/oschameleon/osfuscation.py", line 100, in callback
    check_UDP_probe(pkt, nfq_packet, self.os_pattern)
  File "/home/elephant/Desktop/oschameleon/oschameleon/stack_packet/UDP_.py", line 28, in check_UDP_probe
    send_ICMP_reply(pkt, ICMP_type, os_pattern, os_pattern.TCP_OPTIONS['U1'])
  File "/home/elephant/Desktop/oschameleon/oschameleon/stack_packet/ICMP_.py", line 96, in send_ICMP_reply
    icmp_rpl.send_PUR_packet()
  File "/home/elephant/Desktop/oschameleon/oschameleon/stack_packet/ICMP_.py", line 59, in send_PUR_packet
    send(self.ip / self.icmp / self.pkt, verbose=0)
  File "/home/elephant/.local/lib/python2.7/site-packages/scapy/packet.py", line 281, in __div__
    cloneB = other.copy()
  File "/home/elephant/.local/lib/python2.7/site-packages/scapy/packet.py", line 168, in copy
    clone.payload = self.payload.copy()
  File "/home/elephant/.local/lib/python2.7/site-packages/scapy/packet.py", line 168, in copy
    clone.payload = self.payload.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by manu-g** [comment]
I did have some errors with scapy. Try running it with the following version: 
python-scapy=2.2.0-1
python-gevent=1.0.1-2
python-nfqueue=0.5-1+b1
Does this resolve the error for you?

**Comment by lceames** [comment]
Yes, thanks again. The old version of scapy took care of the bug I was facing. Still working getting an exact OS fingerprint match.

**Comment by glaslos** [comment]
Regarding the scapy issue, it might be worth investigating https://github.com/kbandla/dpkt as a replacement.

**Pull request merged**
